Feature/game display
keykey7/fabbwled pull request #411
Opened 2023-09-25 15:04 UTC by JJoeeyy

### What?

### Why?

### How?

### Testing?

### Screenshots (for frontend changes)

### Anything Else?

[//]: # (for a sample see: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

2023-09-26 07:41 UTC, Oliver-was-taken commented
Please remove .bin from pr and add it to .gitignore

2023-09-26 07:45 UTC, Oliver-was-taken requested changes
Remove node_modules from pr

2023-10-02 09:58 UTC, keykey7 commented
you are allowed to modify (or even drop) `prettifier`, but you have to pass the npm test :P

2023-10-02 13:35 UTC, corsin-lehre requested changes

2023-10-02 13:35 UTC, corsin-lehre commented on package.json
> +  }
This doesn't look quite right... Can you revert this change?

2023-10-02 13:58 UTC, corsin-lehre approved these changes
LGMT

2023-10-02 14:38 UTC, Desi7 approved these changes
Funny thinking to use an eraser, because of the paper 👍 code as well good

2023-10-02 19:03 UTC, Lion-alt approved these changes
Looks good 👍

2023-10-23 14:53 UTC, Desi7 approved these changes
Nice 👍

2023-10-23 14:53 UTC, MagischerWolf05 approved these changes
TOp notch

2023-10-23 14:53 UTC, MagischerWolf05 commented on fabbwled-frontend/src/routes/game/Game.tsx
> +                <li>Profession: Hurensohn</li>
wie bitte

2023-10-23 14:53 UTC, merged