added ability to add acquireKeyword to yaml
keykey7/fabbwled pull request #459
Opened 2023-10-07 12:37 UTC by Lion-alt

### What?
Add acquireKeyword to yaml
### Why?
To finish more sections.
### How?
Edited section-schema.json and a bit of ActionBuilder.
### Testing?

### Screenshots (for frontend changes)

### Anything Else?

2023-10-07 13:13 UTC, Nilstrieb requested changes

2023-10-07 13:13 UTC, Nilstrieb commented on fabbwled-backend/section-schema.json
> +              "type": "keyword"
type should be string

2023-10-07 13:13 UTC, Nilstrieb commented on fabbwled-backend/src/main/java/ch/bbw/fabbwled/lands/service/ShardSystem.java
> +@Getter
nice cleanup :)

2023-10-07 13:14 UTC, Nilstrieb commented
Also make sure to document this property in the Wiki.

2023-10-30 14:46 UTC, Nilstrieb approved these changes

2023-10-30 14:47 UTC, Nilstrieb approved these changes

2023-10-30 14:48 UTC, dbabvwid approved these changes

2023-10-30 14:51 UTC, Rwael approved these changes
Impressively modular architecture! 🧐

2023-10-30 14:52 UTC, adrsch04 approved these changes
looks good

2023-10-30 14:52 UTC, MagischerWolf05 approved these changes
👍

2023-10-30 14:54 UTC, kimberlymo approved these changes
lgtm 👍

2023-10-30 14:56 UTC, merged

2023-10-30 14:58 UTC, lucasmillanm approved these changes
Seems alright