Nils sini Sections
keykey7/fabbwled pull request #504
Opened 2023-11-13 14:58 UTC by dbabvwid

### What?

### Why?

### How?

### Testing?

### Screenshots (for frontend changes)

### Anything Else?

[//]: # (for a sample see: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

2023-11-13 15:00 UTC, Nilstrieb requested changes
Please edit your PR title to something more descriptive

2023-11-13 15:05 UTC, Nilstrieb requested changes
please fix all the missing spaces

2023-11-13 15:05 UTC, Nilstrieb commented on fabbwled-backend/src/main/resources/sections/469-504.yaml
> +        Gain 1 CHARISMApoint permanently. Afterwards, for a few hours, he lifts the cursethat soured your water so you can make it down the mountainpath safely.
```suggestion
        Gain 1 CHARISMA point permanently. Afterwards, for a few hours, he lifts the curse that soured your water so you can make it down the mountainpath safely.
```

2023-11-13 15:05 UTC, Nilstrieb commented on fabbwled-backend/src/main/resources/sections/469-504.yaml
> +        Fort Estgard is one of three forts along the wall that runsright along the border.
```suggestion
        Fort Estgard is one of three forts along the wall that runs right along the border.
```

2023-11-13 15:05 UTC, Nilstrieb commented on fabbwled-backend/src/main/resources/sections/469-504.yaml
> +        It is said that the god, Sig, in his aspect as the DivineBard, passed this knowledge to a mystic called Damor theHermit.
```suggestion
        It is said that the god, Sig, in his aspect as the Divine Bard, passed this knowledge to a mystic called Damor theHermit.
```

2023-11-13 18:43 UTC, Lion-alt approved these changes
LGTM 👍

2023-11-20 14:56 UTC, Nilstrieb requested changes

2023-11-20 14:56 UTC, Nilstrieb commented on fabbwled-backend/src/main/resources/sections/469-504.yaml
> +        You are not being cruel for the sake of it – she was about to steal your money!‘Oh, let me go,’ she pleads, showing you the little infant son she’s carrying in her other arm.
```suggestion
        You are not being cruel for the sake of it – she was about to steal your money! ‘Oh, let me go,’ she pleads, showing you the little infant son she’s carrying in her other arm.
```

2023-11-20 14:56 UTC, Nilstrieb commented on fabbwled-backend/src/main/resources/sections/469-504.yaml
> +        With a snarl, you push her away, tossing a coin after her for good measure (cross 1Shard off your Adventure Sheet).
```suggestion
        With a snarl, you push her away, tossing a coin after her for good measure (cross 1 Shard off your Adventure Sheet).
```

2023-11-20 14:56 UTC, Nilstrieb commented on fabbwled-backend/src/main/resources/sections/469-504.yaml
> +        The commander of the fort desperately wants to see you.‘My daughter, Alissia, has been kidnapped by the man beasts!’he says.
```suggestion
        The commander of the fort desperately wants to see you.‘My daughter, Alissia, has been kidnapped by the man beasts!’ he says.
```

2023-11-20 14:57 UTC, Nilstrieb commented
still many missing spaces

2023-11-20 15:00 UTC, Nilstrieb requested changes
there are still missing spaces

2023-11-20 15:11 UTC, Nilstrieb approved these changes
The sun sets over the small town. All words get back into their houses, each having enough space. They rest.

2023-11-20 15:44 UTC, tamer545 approved these changes

2023-11-20 15:47 UTC, MagischerWolf05 approved these changes
sounds good

2023-11-20 15:57 UTC, lucasmillanm approved these changes

2023-11-20 19:37 UTC, Noeell requested changes
Please make sure that the checks pass...

2023-12-11 15:20 UTC, Nilstrieb commented
@dbabvwid please update your PR

2023-12-18 15:21 UTC, Nilstrieb approved these changes

2023-12-18 15:22 UTC, Nilstrieb commented
noel said he approves

2023-12-18 19:26 UTC, Noeell approved these changes
Please link your issues before merging.

2024-01-08 14:58 UTC, merged