Easy sections 613 648
keykey7/fabbwled pull request #553
Opened 2023-11-20 15:41 UTC by Oliver-was-taken

### What?

### Why?

All currently implementable sections from 613-648
prettier :)

### How?

add sections to yaml

### Testing?

### Screenshots (for frontend changes)

### Anything Else?

[//]: # (for a sample see: https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)

2023-11-20 15:45 UTC, MagischerWolf05 approved these changes
sounds Greate

2023-11-20 15:50 UTC, keykey7 commented on fabbwled-backend/src/main/resources/application.yaml
> +    path: "/api-docs"
note that the current `.editorconfig` states `insert_final_newline = false`
while I am not a fan of this setting, that's currently the contract. if you deliberately want to update it, also reflect it in the `.editorconfig` file.

2023-11-20 15:52 UTC, Nilstrieb requested changes
Haven't reviewed the second half yet, but some feedback on the first half

2023-11-20 15:52 UTC, Nilstrieb commented on fabbwled-backend/src/main/resources/sections/613-648.yaml
> +        If you lose, your adventures are over, unless you have a resurrection deal.
this should like, actually contain a fight. comment it out as too complex

2023-11-20 15:52 UTC, Nilstrieb commented on fabbwled-backend/src/main/resources/sections/613-648.yaml
> +        have finished here, turn to 544.
this is an if, and cannot be represented like that. also the god

2023-11-20 15:52 UTC, Nilstrieb commented on fabbwled-backend/src/main/resources/sections/613-648.yaml
> +        examine the magic chest , but it is guarded by great sorcery and
```suggestion
        examine the magic chest, but it is guarded by great sorcery and
```

2023-11-20 15:52 UTC, Nilstrieb commented on fabbwled-backend/src/main/resources/sections/613-648.yaml
> +    - acquireKeyword: Avenge
that's not acquire, it should be deleted

2023-11-20 15:52 UTC, Nilstrieb commented on fabbwled-backend/src/main/resources/sections/613-648.yaml
> +        COMBAT bonus +1 – 200 Shards
needs a marketplace, make it TODO

2023-11-20 15:52 UTC, Nilstrieb commented on fabbwled-backend/src/main/resources/sections/613-648.yaml
> +        of Tyrnai. Subtract 1 from your COMBAT ability until you can
can't do this, TODO

2023-11-20 15:52 UTC, Nilstrieb commented on fabbwled-backend/src/main/resources/sections/613-648.yaml
> +        +2) are pushed towards you. Note them on your Adventure
note them on the adventure sheet - cant do this

2023-11-20 15:54 UTC, lucasmillanm approved these changes
Seems alright

2023-11-20 16:09 UTC, Lion-alt approved these changes
LGTM 👍  A test should be writen to catch those syntax errors...

2023-11-21 11:50 UTC, Noeell requested changes
Please link section-issues

2023-11-21 11:50 UTC, Noeell commented on fabbwled-backend/src/main/resources/sections/613-648.yaml
> +        If you have the codeword Apple , turn to 594 . If not, you
```suggestion
        If you have the codeword Apple , turn to 594 . If not, you can:
```

Maybe add can: here?

2023-11-21 11:50 UTC, Noeell commented on fabbwled-backend/src/main/resources/sections/613-648.yaml
> +        an uneventful evening, turn to 100 .
```suggestion
        an uneventful evening, turn to 100.
```

2023-11-21 11:50 UTC, Noeell commented on fabbwled-backend/src/main/resources/sections/613-648.yaml
> +        Turn to 400 .
```suggestion
        Turn to 400.
```

2023-11-21 11:50 UTC, Noeell commented on fabbwled-backend/src/main/resources/sections/613-648.yaml
> +        while they sleep. Turn to 554 .
```suggestion
        while they sleep. Turn to 554.
```

2023-11-21 11:50 UTC, Noeell commented on fabbwled-backend/src/main/resources/sections/613-648.yaml
> +        the Bronze Hills. Turn to 110 .
```suggestion
        the Bronze Hills. Turn to 110.
```

2023-11-21 11:50 UTC, Noeell commented on fabbwled-backend/src/main/resources/sections/613-648.yaml
> +        leave the tavern. Turn to 10
```suggestion
        leave the tavern. Turn to 10.
```

2023-11-21 11:50 UTC, Noeell commented on fabbwled-backend/src/main/resources/sections/613-648.yaml
> +        Curse, -1 COMBAT. You sneak out of the temple. Turn to 400 .
```suggestion
        Curse, -1 COMBAT. You sneak out of the temple. Turn to 400.
```

2023-11-21 11:50 UTC, Noeell commented on fabbwled-backend/src/main/resources/sections/613-648.yaml
> +        When you have finished here, turn to 220 .
```suggestion
        When you have finished here, turn to 220.
```

2023-11-21 11:50 UTC, Noeell commented on fabbwled-backend/src/main/resources/sections/613-648.yaml
> +        Delete the codeword Avenge and turn to 135 .
```suggestion
        Delete the codeword Avenge and turn to 135.
```

2023-11-27 15:19 UTC, Noeell approved these changes
LGTM 👍

2023-11-27 15:21 UTC, Nilstrieb approved these changes

2023-11-27 15:33 UTC, merged