Don't make JSESSIONID http-only
keykey7/fabbwled pull request #580
Opened 2023-12-04 15:21 UTC by Nilstrieb

This allows the frontend to manipulate it to implement different save games.

There is no security to be lost.

### What?

Don't make the session ID http only.

### Why?

So the frontend could access it in the future. It is not clear whether this is needed today, but there's no reason not to do this.

### How?

By changing the config

### Testing?

I have no tested it but don't want to

2023-12-04 15:39 UTC, kaibria approved these changes
for me okay

2023-12-04 16:12 UTC, keykey7 requested changes
by allowing JS to read the cookie we open up to XSS stealing it.
but my main argument would be: FE doesn't need to know... they just start calling endpoints and immediately get a SESSIONID. 
if the use-case is: FE wants to know if they played before: provide a new endpoint (or a defined exception on /api/player). The cookie mechanic is a technical detail transparent to FE.

2023-12-04 19:16 UTC, Lion-alt approved these changes
Looks good 👍

2023-12-11 15:13 UTC, Nilstrieb commented
doesn't really matter

2023-12-11 15:13 UTC, closed without merging